version: '3'
services:
  backend:
    build: ./backendapp
    ports:
      - "5001:8000"
  frontend:
    build: ./frontendapp
    ports:
      - "5002:8501"
networks:
  backend-network:
  driver: bridge