version: '3'
services:
  backend:
    build: ./backendapp
    ports:
      - "8000:8000"
    networks:
      - backend-network

  frontend:
    build: ./frontendapp
    ports:
      - "5002:80"
    depends_on:
      - backend

networks:
  backend-network: