# set base image (host OS)
FROM python:3.10

#install update
RUN apt-get update

# set the working directory in the container
WORKDIR /code

# copy the dependencies file to the working directory
COPY requirements.txt .

# install dependencies
RUN pip install -r requirements.txt

# copy the content of the local src directory to the working directory
COPY src/ .

# command to run on container start
CMD ["streamlit", "run" "main.py"]